version: 2
jobs:
  build:
    working_directory: /opt/iroha
    docker:
      - image: warchantua/iroha-dev
    steps:
      - checkout:
      - run: 
          name: build directory
          command: |
            mkdir -p $IROHA_BUILD
            cd $IROHA_BUILD

      - run:
          name: cmake
          command: cmake $IROHA_HOME
      - run:
          name: make
          command: make -j4
